name: Bump Semver

on:
  push:
    paths:
      - "version.properties"
    # tags:
    #   - "chore(release): prepare for *"

jobs:
  bump-ver:
    name: Bump Semver
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      - name: Read Project Version
        id: mod-version
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "version.properties"
          properties: "version"

      - name: Bump Version (fabric.mod.json)
        uses: restackio/update-json-file-action@2.1
        with:
          file: fabric.mod.json
          fields: "{\"version\": \"${{ steps.mod-version.outputs.version }}\"}"

      - name: Bump Version (quilt.mod.json)
        uses: restackio/update-json-file-action@2.1
        with:
          file: quilt.mod.json
          fields: "{\"quilt_loader.version\": \"${{ steps.mod-version.outputs.version }}\"}"

      - name: Merge to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "v${{ steps.mod-version.outputs.version }}"
          git push